### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by lopugit** [verbb/formie-headless#2]
Is there extra work required to get file upload field working? It doesn't seem to work by default.

Kind regards

**Comment by lopugit** [comment]
It creates the sub folder but no file is uploaded. This is using the apollo mutation method

**Comment by lopugit** [comment]
I have tried setting the public schema to allow creating assets under the selected Volume

**Comment by lopugit** [comment]
So it looks like the `FormDataJson.fromToJson(el)` doesn't do anything with file upload inputs, now I'm researching how to programmatically upload files to Craft CMS separately

**Comment by lopugit** [comment]
I'm worried this won't work with the submitted field though, the submitted asset field will always be empty. Any advice?

**Comment by engram-design** [comment]
There shouldn't be anything extra you need to do to allow uploading of assets via GraphQL. However, just testing things out again and _something_ has changed that used to work. The [form-data-json](https://github.com/brainfoolong/form-data-json) library has since been updated with some breaking changes that do support file inputs, but that's going to require some refactoring on my end, and figure out a way to submit a base64 string to the GQL mutation instead of the expected Asset ID.

**Comment by lopugit** [comment]
> There shouldn't be anything extra you need to do to allow uploading of assets via GraphQL. However, just testing things out again and _something_ has changed that used to work. The [form-data-json](https://github.com/brainfoolong/form-data-json) library has since been updated with some breaking changes that do support file inputs, but that's going to require some refactoring on my end, and figure out a way to submit a base64 string to the GQL mutation instead of the expected Asset ID.

I've tested the new V2 FormDataJson, 

I replaced the call with a Promise that converts the file from base64 to Array Buffer as the field is set to an `[INT]` type so I'm guessing you guys wanted it to be an ArrayBuffer? The build in `fileReaderFunction: 'readAsArrayBuffer'` option for FormDataJson doesn't seem to work so converting from base64 is the way to go.

```javascript
  // mutations.js:78
  const object = await new Promise((resolve, reject) => {
    FormDataJson.toJson(el, {
      // fileReaderFunction: 'readAsArrayBuffer',
      filesCallback(values) {
        console.log('values', values)
        for (const key in values) {
          const value = values[key]
          if (value.includes('data:image/png;base64')) {
            values[key] = Uint8Array.from(
              atob(value.split('data:image/png;base64,')[1]),
              (c) => c.charCodeAt(0)
            )
          }
        }
        resolve(values)
      },
    })
  })
```

Apparently it needs to be a promise because reading the file input isn't synchronous..

Just need to make onSubmit an async and await the getMutationVariables function, make that async too. 

That seems to have got the file upload submitting to Craft, but now I'm faced with this response from Apollo/Craft CMS

```"SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`craft3_starter_dev`.`relations`, CONSTRAINT `fk_usjgouhtgufformbhescnwklshztvbqflnjt` FOREIGN KEY (`targetId`) REFERENCES `elements` (`id`) ON DELETE CASCADE)"```

<img width="1489" alt="Screen Shot 2022-06-02 at 3 38 50 pm" src="https://user-images.githubusercontent.com/13629190/171560427-e04c08d1-3e64-475d-ab79-390fd0b3f378.png">

**Comment by engram-design** [comment]
I'll mention that the `filesCallback` is buggy in that it doesn't fire if the form contains a file input, but no file was provided, so looking at potential alternatives to that library.

But yes, we'll need to tweak the expected types for mutations. Just need to review this as a potential breaking change.

That error usually means the file upload hasn't been performed correctly, so looking into it.

**Comment by lopugit** [comment]
@engram-design nice nice, let's work together on this maybe. I noticed you're in Melbourne too haha, I work at Thirst Creative in Carlton. Nice to meet you. 

Would be great to get this functioning, I'm happy to help as much as I can. 

Thanks for being so responsive :) 🚀

**Comment by lopugit** [comment]
Also no rush, we're just trialling this to add to our stack so, would just be awesome to get it working for everyone's sake

**Comment by lopugit** [comment]
By the way, is Formie open source, I would be happy to look into it a bit.

I found this answer explaining it a bit: https://craftcms.stackexchange.com/questions/26917/randomly-getting-the-integrity-constraint-violation-sql-error-on-saving-entry

As you said it may be that the upload is failing, causing some kind of Asset ID mismatch or something.

<img width="1470" alt="Screen Shot 2022-06-02 at 4 07 55 pm" src="https://user-images.githubusercontent.com/13629190/171564196-f5977c25-a2cc-43a1-8f21-1856dfd2e720.png">

**Comment by engram-design** [comment]
Oh, nice to meet a local! 🇦🇺 And leave it with me for a bit, I'll continue to figure a solution out. Craft will require a blob for asset uploads (the type that a normal form submission or `FormData` would produce), so I'll investigate further.

**Comment by engram-design** [comment]
Alrighty, so I've had to make some changes on [Formie's end](https://github.com/verbb/formie/commit/0eba4a1aaaf8b2cc00ed1839ebc57eb28dfc26b0) to handle file uploads better now. Formie will now accept an array of objects with a base64-encoded string (and optionally a filename) and upload that. This mimics Craft's Asset element-upload handling for GraphQL (when using mutations to create assets) - but this doesn't exist for asset fields, just asset elements.

So the format:

```json
{
  "fileInputField": [
    {
      "fileData": "data:image/png;base64,iVBORw0KGgoAA...",
      "filename": "testing.png"
    },
    {
      "fileData": "data:image/png;base64,iVBORw0KGgoAA..."
    }
  ]
}
```

To get this change early, change your `verbb/formie` requirement in `composer.json` to:

```
"require": {
  "verbb/formie": "dev-craft-3 as 1.5.18",
  "...": "..."
}
```

Then run `composer update`. 

On the client-side however, I'm still not fully happy with [form-data-json](https://github.com/brainfoolong/form-data-json) for the reasons mentioned above (callback doesn't fire if file input left empty).

So while I'm going to take a little bit more time to come up with some polish here for this demo project, you're welcome to jump in and put together your own solution. This should get you started:

```js
import FormDataJson from 'form-data-json-convert';
import { flatMap, isPlainObject, isString } from 'lodash-es';

const object = await new Promise((resolve, reject) => {
        FormDataJson.toJson(el, {
            filesCallback(values, v) {
                for (const key in values) {
                    const value = values[key];

                    // Handle single-file input values, which are data values
                    if (isString(value) && value.includes('data:')) {
                        values[key] = [{
                            fileData: value,

                            // TODO: find a way to get the filename as well
                            // filename: '',
                        }];
                    }
                }
                resolve(values);
            },
        });
    });
```

But note this doesn't handle:
- Filenames, which could probably be grabbed from `$input.files`
- Multi-file capable inputs - this assumes you have a single-file input

I'll likely ditch the callback, and build the input data myself for this reason.

**Comment by lopugit** [comment]
@engram-design wow thanks heaps, it's looking good.

Did you change something that requires this fragment to be changed from `fragment FormFragment on Form {` to `fragment FormFragment on specificForm_Form {`?

Because my Apollo started throwing an error saying that the Form `Tried to load an unregistered type "Form".`

In the explorer it used to just have Form as well but now it has the specific forms to select from.

![Screen Shot 2022-06-03 at 11 05 10 am](https://user-images.githubusercontent.com/13629190/171767394-5cbad1a2-b39e-4db1-8253-f70c76aff149.png)

**Comment by lopugit** [comment]
Ah ok you can just change it to `FormInterface`

**Comment by engram-design** [comment]
Oh, sorry yes that's another change. There's now no longer a global `Form` fragment, which was silly anyway. You can now use a per-form based fragment, or my change here should suffice: https://github.com/verbb/formie-headless/commit/21acfdd2c832b4038f122c1b554d1777e77d9d89

**Comment by lopugit** [comment]
Ayeeeeeee it's working, thanks a lot man, I'll see if I can implement this conditional logic and make a PR to the starter

**Comment by lopugit** [comment]
For filenames

```javascript
const object = await new Promise((resolve, reject) => {
    const files = {}
    FormDataJson.toJson(el, {
      inputFilter(field) {
        if (field.type === 'file') {
          files[field.id] = field.value.replace('C:\\fakepath\\', '')
        }
        return true
      },
      filesCallback(values, v) {
        for (const key in values) {
          const value = values[key]

          // Handle single-file input values, which are data values
          if (isString(value) && value.includes('data:')) {
            values[key] = [
              {
                fileData: value,

                // TODO: find a way to get the filename as well
                filename: files[key],
              },
            ]
          }
        }
        resolve(values)
      },
    })
  })
```
